package com.example.yasinreel.deck

import com.example.yasinreel.llm.FallbackDirector
import com.example.yasinreel.model.Audience
import com.example.yasinreel.model.Evidence
import com.example.yasinreel.model.ProductModel
import com.example.yasinreel.model.Scene
import com.example.yasinreel.model.SceneTemplate
import com.example.yasinreel.model.Storyboard
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

/**
 * Builds a [Deck] for one audience. Deterministic, and deliberately so.
 *
 * The plan for this started with a third AI call, a deck director sitting beside the two
 * film directors. Writing it out made clear that would be a call added for its own sake.
 * [ProductModel] was already designed to serve two audiences: a capability carries both
 * a `userFacingName` with a `userBenefit` and a `technicalSummary`, and the model already
 * holds a problem statement, a target user, layers, flows, a stack, measurements and an
 * honest list of gaps. That is a deck outline. Projecting it costs no latency, adds no
 * new prompt to get wrong, and makes it impossible for the deck to contradict the film,
 * because both are reading the same understanding.
 *
 * The AI is still what makes this possible. It just already ran, in stage 2, and its
 * result is cached, which is why a deck arrives in about a second on a project whose
 * film has already been made.
 *
 * Two entry points, matching the film's two paths:
 *  - [fromModel] when stage 2 produced a [ProductModel]
 *  - [fromEvidence] when there was no key and nothing but harvested facts
 */
object DeckComposer {

    private val STAMP: DateTimeFormatter = DateTimeFormatter.ofPattern("d MMMM yyyy", Locale.ENGLISH)

    fun fromModel(model: ProductModel, evidence: Evidence, audience: String): Deck {
        val stakeholder = audience == Audience.STAKEHOLDER
        val slides = mutableListOf<Slide>()

        slides += slide(SlideLayout.TITLE, obj {
            put("productName", model.productName)
            put("tagline", model.tagline)
            put("project", evidence.projectName)
            put("stamp", "${audienceLabel(audience)}  ·  ${LocalDate.now().format(STAMP)}")
        }, if (stakeholder) {
            "Everything in this deck was worked out from the product itself, so every number on it is real rather than illustrative."
        } else {
            "This deck was generated from the codebase itself. Every number and every name on the following slides came out of the repository, not out of a template."
        })

        // Built last but inserted here, once the deck knows what it actually contains.
        val agendaAt = slides.size
        slides += problemSlide(model, stakeholder)

        if (stakeholder) {
            slides += slide(SlideLayout.STATEMENT, obj {
                put("statement", model.tagline)
                put("attribution", "For ${model.targetUser}")
            }, "This is the promise in one line. Everything after this slide is evidence for it.")
            journeySlide(model)?.let { slides += it }
        } else {
            architectureSlide(model)?.let { slides += it }
            flowSlide(model)?.let { slides += it }
            stackSlide(model)?.let { slides += it }
        }

        capabilitySlides(model, stakeholder).forEach { slides += it }
        statsSlide(model, evidence, stakeholder)?.let { slides += it }
        gapsSlide(model, stakeholder)?.let { slides += it }

        slides += slide(SlideLayout.CLOSING, obj {
            put("headline", if (stakeholder) model.tagline else "${model.productName}, end to end")
            put("stamp", "${evidence.projectName}  ·  generated by Nexus on ${LocalDate.now().format(STAMP)}")
        }, if (stakeholder) {
            "Close here. Everything shown was worked out from the product itself, so any of it can be traced back to the thing that was actually built."
        } else {
            "Close here. The deck and the video were both generated from this codebase, so anything on them can be traced back to a file."
        })

        slides.add(agendaAt, agendaFor(slides, stakeholder))

        return Deck(
            audience = audience,
            title = model.productName,
            subtitle = model.tagline,
            projectName = evidence.projectName,
            slides = slides.take(Caps.MAX_SLIDES)
        )
    }

    /**
     * The no-key path.
     *
     * Rather than a second set of rules for building slides out of raw facts, this
     * converts what [FallbackDirector] already produces. That director was written and
     * corrected against the one complaint that mattered most on this project, that a
     * stakeholder must never be shown a file path or the word endpoint, and rewriting
     * that judgement here would mean rediscovering it.
     */
    fun fromEvidence(evidence: Evidence, audience: String): Deck {
        val storyboard = FallbackDirector.direct(evidence, audience, 60_000)
        val stakeholder = audience == Audience.STAKEHOLDER
        val slides = storyboard.scenes.mapNotNull { fromScene(it, evidence, audience) }.toMutableList()

        val agendaAt = minOf(1, slides.size)
        if (slides.size >= Caps.MIN_SLIDES - 1) {
            slides.add(agendaAt, agendaFor(slides, stakeholder))
        }
        return Deck(
            audience = audience,
            title = storyboard.theme.projectName.ifBlank { evidence.projectName },
            subtitle = evidence.readme?.let { firstSentence(it) }.orEmpty(),
            projectName = evidence.projectName,
            slides = slides.take(Caps.MAX_SLIDES)
        )
    }

    // ------------------------------------------------------------ model slides

    private fun problemSlide(model: ProductModel, stakeholder: Boolean): Slide =
        slide(SlideLayout.PROBLEM, obj {
            put("eyebrow", "The problem")
            put("heading", if (stakeholder) "Why this exists" else "What it solves")
            put("body", model.problemStatement)
            put("context", "Built for ${model.targetUser}.")
        }, "Open on the problem, not the product. ${model.problemStatement}")

    private fun architectureSlide(model: ProductModel): Slide? {
        val layers = model.architecture.layers.take(Caps.MAX_LAYERS)
        if (layers.isEmpty()) return null
        return slide(SlideLayout.ARCH_LAYERS, obj {
            put("eyebrow", "Architecture")
            put("heading", "How it is put together")
            put("layers", array(layers) { layer ->
                obj {
                    put("name", layer.name)
                    put("components", array(layer.components.take(Caps.MAX_COMPONENTS)) { component ->
                        primitive(component.tech?.takeIf { it.isNotBlank() }?.let { "${component.name} · $it" } ?: component.name)
                    })
                }
            })
        }, "Walk down the layers. " + layers.joinToString("; ") { "${it.name}: ${it.components.take(3).joinToString(", ") { c -> c.name }}" })
    }

    private fun flowSlide(model: ProductModel): Slide? {
        val flow = model.keyFlows.firstOrNull() ?: return null
        val steps = flow.steps.take(Caps.MAX_STEPS)
        if (steps.isEmpty()) return null
        return slide(SlideLayout.FLOW, obj {
            put("eyebrow", "One request, end to end")
            put("heading", flow.name)
            put("steps", array(steps) { step ->
                obj {
                    put("label", step.actor)
                    put("detail", step.action)
                }
            })
        }, "This is the path a single piece of work takes through the system: " +
            steps.joinToString(", then ") { "${it.actor} ${it.action}" } + ".")
    }

    private fun stackSlide(model: ProductModel): Slide? {
        val byCategory = model.techStack
            .filter { it.name.isNotBlank() }
            .groupBy { it.category.ifBlank { "Other" } }
        if (byCategory.isEmpty()) return null
        val groups = byCategory.entries.sortedByDescending { it.value.size }.take(Caps.MAX_GROUPS)
        return slide(SlideLayout.STACK, obj {
            put("eyebrow", "The stack")
            put("heading", "What it is built on")
            put("groups", array(groups) { entry ->
                obj {
                    put("category", entry.key)
                    put("items", array(entry.value.take(Caps.MAX_GROUP_ITEMS)) { primitive(it.name) })
                }
            })
        }, "The stack, and the reasons behind it. " +
            groups.flatMap { it.value }.take(3).joinToString(" ") { "${it.name}: ${it.why}" })
    }

    private fun journeySlide(model: ProductModel): Slide? {
        val flow = model.keyFlows.firstOrNull() ?: return null
        val steps = flow.steps.take(Caps.MAX_STEPS)
        if (steps.isEmpty()) return null
        return slide(SlideLayout.JOURNEY, obj {
            put("eyebrow", "What happens")
            put("heading", flow.name)
            put("steps", array(steps) { step ->
                obj {
                    put("actor", step.actor)
                    put("action", step.action)
                }
            })
        }, "Told as something a person does, not as something the software does: " +
            steps.joinToString(", then ") { "${it.actor} ${it.action}" } + ".")
    }

    /**
     * Capabilities, split across as many slides as it takes.
     *
     * Six to a slide, because seven small cards is a slide nobody reads and two slides of
     * four is a deck that keeps its pace.
     */
    private fun capabilitySlides(model: ProductModel, stakeholder: Boolean): List<Slide> {
        val all = model.capabilities.filter { it.userFacingName.isNotBlank() }
        if (all.isEmpty()) return emptyList()
        val perSlide = if (all.size <= 6) all.size else 4
        return all.chunked(perSlide).take(2).mapIndexed { index, chunk ->
            slide(SlideLayout.CAPABILITY_GRID, obj {
                put("eyebrow", if (index == 0) "What it does" else "What it does, continued")
                put("heading", if (stakeholder) "What you can do with it" else "Capabilities")
                put("cards", array(chunk) { capability ->
                    obj {
                        put("title", capability.userFacingName)
                        put("body", if (stakeholder) capability.userBenefit else capability.technicalSummary)
                    }
                })
            }, chunk.joinToString(" ") { "${it.userFacingName}: ${it.userBenefit}" })
        }
    }

    private fun statsSlide(model: ProductModel, evidence: Evidence, stakeholder: Boolean): Slide? {
        val facts = model.scaleFacts
            .filter { it.label.isNotBlank() && it.value.isNotBlank() }
            .take(Caps.MAX_STATS)
            .ifEmpty {
                // The model is allowed to have no measurements; the harvester always has some.
                listOfNotNull(
                    evidence.stats.totalFiles.takeIf { it > 0 }?.let { "Files" to group(it) },
                    evidence.stats.totalLines.takeIf { it > 0 }?.let { "Lines of source" to group(it) },
                    evidence.dependencies.size.takeIf { it > 0 }?.let { "Dependencies" to group(it) },
                    evidence.languages.size.takeIf { it > 0 }?.let { "Languages" to group(it) }
                ).take(Caps.MAX_STATS).map { (label, value) -> com.example.yasinreel.model.ScaleFact(label, value, null) }
            }
        if (facts.isEmpty()) return null
        return slide(SlideLayout.STATS, obj {
            put("eyebrow", "By the numbers")
            put("heading", if (stakeholder) "The size of what was built" else "The shape of it")
            put("stats", array(facts) { fact ->
                obj {
                    put("value", fact.value)
                    put("label", fact.label)
                }
            })
        }, "Every one of these was counted, not estimated: " +
            facts.joinToString(", ") { "${it.value} ${it.label.lowercase()}" } + ".")
    }

    /**
     * The gaps, which are the slide most decks leave out.
     *
     * This project's own charter says never to invent a relationship and to keep
     * unsupported results visible, and a deck that claims a system is finished when the
     * analysis found no tests is exactly that kind of invention. For a stakeholder the
     * same list is framed as what comes next, which is the honest reading of it.
     */
    private fun gapsSlide(model: ProductModel, stakeholder: Boolean): Slide? {
        val items = model.gaps.filter { it.isNotBlank() }.take(Caps.MAX_BULLETS)
        if (items.isEmpty()) return null
        return slide(SlideLayout.GAPS, obj {
            put("eyebrow", if (stakeholder) "What is next" else "Known gaps")
            put("heading", if (stakeholder) "Where this goes from here" else "What the analysis could not find")
            put("framing", if (stakeholder) {
                "These are the things the product does not do yet."
            } else {
                "Listed rather than hidden. Each one is something the harvest looked for and did not find."
            })
            put("items", array(items) { primitive(it) })
        }, "Say this out loud rather than skipping it. Being the person who names the gaps is what makes the rest of the deck believable.")
    }

    // --------------------------------------------------------- evidence slides

    /** Maps one film scene onto the slide layout that carries the same idea. */
    private fun fromScene(scene: Scene, evidence: Evidence, audience: String): Slide? {
        val slots = scene.slots.deepCopy()
        val notes = scene.narration.orEmpty()
        return when (scene.template) {
            SceneTemplate.TITLE -> {
                slots.addProperty("project", evidence.projectName)
                slots.addProperty("stamp", "${audienceLabel(audience)}  ·  ${LocalDate.now().format(STAMP)}")
                Slide(SlideLayout.TITLE, slots, notes)
            }
            SceneTemplate.BIG_STATEMENT -> Slide(SlideLayout.STATEMENT, slots, notes)
            SceneTemplate.STAT_GRID -> Slide(SlideLayout.STATS, slots, notes)
            SceneTemplate.CAPABILITY_CARDS -> Slide(SlideLayout.CAPABILITY_GRID, slots, notes)
            SceneTemplate.ARCH_LAYERS -> Slide(SlideLayout.ARCH_LAYERS, slots, notes)
            SceneTemplate.FLOW_TRACE -> Slide(SlideLayout.FLOW, slots, notes)
            SceneTemplate.JOURNEY -> Slide(SlideLayout.JOURNEY, slots, notes)
            SceneTemplate.OUTRO -> {
                slots.addProperty("stamp", "${evidence.projectName}  ·  generated by Nexus")
                Slide(SlideLayout.CLOSING, slots, notes)
            }
            else -> null
        }
    }

    // -------------------------------------------------------------- the agenda

    /**
     * Built from the deck rather than written for it, so it can never promise a slide
     * that is not there. That is also why it is inserted after everything else exists.
     */
    private fun agendaFor(slides: List<Slide>, stakeholder: Boolean): Slide {
        val items = slides
            .filter { it.layout != SlideLayout.TITLE && it.layout != SlideLayout.CLOSING }
            .mapNotNull { agendaLabel(it) }
            .distinct()
            .take(Caps.MAX_AGENDA)
        return slide(SlideLayout.AGENDA, obj {
            put("eyebrow", "Agenda")
            put("heading", if (stakeholder) "What we will cover" else "What this covers")
            put("items", array(items) { label -> obj { put("label", label) } })
        }, "Thirty seconds on this slide. It exists so nobody in the room is wondering how long this will take.")
    }

    private fun agendaLabel(slide: Slide): String? {
        val heading = slide.slots.get("heading")?.takeIf { it.isJsonPrimitive }?.asString?.trim()
        if (!heading.isNullOrEmpty()) return DeckTheme.clip(heading, Caps.AGENDA_ITEM)
        return when (slide.layout) {
            SlideLayout.PROBLEM -> "The problem"
            SlideLayout.STATEMENT -> "The promise"
            SlideLayout.CAPABILITY_GRID -> "What it does"
            SlideLayout.ARCH_LAYERS -> "Architecture"
            SlideLayout.FLOW -> "One request, end to end"
            SlideLayout.STATS -> "By the numbers"
            SlideLayout.STACK -> "The stack"
            SlideLayout.JOURNEY -> "What happens"
            SlideLayout.GAPS -> "What is next"
            else -> null
        }
    }

    // ------------------------------------------------------------------ plumbing

    private fun slide(layout: String, slots: JsonObject, notes: String): Slide =
        Slide(layout, slots, DeckTheme.clip(notes, Caps.NOTES))

    private fun obj(build: JsonObject.() -> Unit): JsonObject = JsonObject().apply(build)

    private fun <T> array(items: Iterable<T>, map: (T) -> com.google.gson.JsonElement): JsonArray =
        JsonArray().apply { items.forEach { add(map(it)) } }

    private fun primitive(value: String): com.google.gson.JsonElement =
        com.google.gson.JsonPrimitive(value)

    private fun JsonObject.put(key: String, value: String?) {
        if (!value.isNullOrBlank()) addProperty(key, value.replace(Regex("\\s+"), " ").trim())
    }

    private fun JsonObject.put(key: String, value: JsonArray) {
        if (value.size() > 0) add(key, value)
    }

    private fun group(value: Int): String =
        value.toString().reversed().chunked(3).joinToString(",").reversed()

    private fun audienceLabel(audience: String): String =
        if (audience == Audience.STAKEHOLDER) "Stakeholder deck" else "Technical deck"

    private fun firstSentence(readme: String): String {
        val clean = readme.lineSequence()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") && !it.startsWith("[!") && !it.startsWith("<") }
            .firstOrNull()
            .orEmpty()
        return DeckTheme.clip(clean.substringBefore(". ").removeSuffix("."), Caps.DECK_SUBTITLE)
    }
}
